import 'package:hive_flutter/hive_flutter.dart';
import '../models/expense_model.dart';
import '../models/income_model.dart';
import '../models/category_model.dart';
import '../models/workout_model.dart';
import '../models/work_task_model.dart';

/// Hive storage service for local persistence
class StorageService {
  static const String expenseBoxName = 'expenses';
  static const String incomeBoxName = 'incomes';
  static const String categoryBoxName = 'categories';
  static const String workoutBoxName = 'workouts';
  static const String workTaskBoxName = 'work_tasks';
  
  /// Initialize Hive and register adapters
  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters (generated by build_runner)
    Hive.registerAdapter(ExpenseModelAdapter());
    Hive.registerAdapter(IncomeModelAdapter());
    Hive.registerAdapter(CategoryModelAdapter());
    Hive.registerAdapter(WorkoutModelAdapter());
    Hive.registerAdapter(WorkTaskModelAdapter());
    Hive.registerAdapter(TaskTypeAdapter());
    Hive.registerAdapter(TaskPriorityAdapter());
    
    // Open boxes
    await Hive.openBox<ExpenseModel>(expenseBoxName);
    await Hive.openBox<IncomeModel>(incomeBoxName);
    await Hive.openBox<CategoryModel>(categoryBoxName);
    await Hive.openBox<WorkoutModel>(workoutBoxName);
    await Hive.openBox<WorkTaskModel>(workTaskBoxName);
    
    // Initialize default categories if empty
    await _initializeDefaultCategories();
  }
  
  /// Initialize default protected categories (work, fitness, finance)
  static Future<void> _initializeDefaultCategories() async {
    final categoryBox = Hive.box<CategoryModel>(categoryBoxName);
    
    // Korumalı kategorileri sil ve yeniden oluştur (ikonları düzeltmek için)
    await categoryBox.delete('work');
    await categoryBox.delete('fitness');
    await categoryBox.delete('finance');
    
    final defaultCategories = [
      CategoryModel(
        id: 'work',
        name: 'İş / Emlak',
        iconCodePoint: 0xe24d, // Icons.folder_outlined
        isProtected: true,
      ),
      CategoryModel(
        id: 'fitness',
        name: 'Spor',
        iconCodePoint: 0xe3a0, // Icons.fitness_center (dumbbell)
        isProtected: true,
      ),
      CategoryModel(
        id: 'finance',
        name: 'Finans',
        iconCodePoint: 0xe227, // Icons.attach_money (dolar)
        isProtected: true,
      ),
    ];
    
    for (var category in defaultCategories) {
      await categoryBox.put(category.id, category);
    }
  }
  
  // Expense operations
  static Box<ExpenseModel> get expenseBox => Hive.box<ExpenseModel>(expenseBoxName);
  
  static Future<void> addExpense(ExpenseModel expense) async {
    await expenseBox.put(expense.id, expense);
  }
  
  static Future<void> deleteExpense(String id) async {
    await expenseBox.delete(id);
  }
  
  static List<ExpenseModel> getExpensesByDate(DateTime date) {
    return expenseBox.values.where((expense) {
      return expense.date.year == date.year &&
             expense.date.month == date.month &&
             expense.date.day == date.day;
    }).toList();
  }
  
  // Income operations
  static Box<IncomeModel> get incomeBox => Hive.box<IncomeModel>(incomeBoxName);
  
  static Future<void> addIncome(IncomeModel income) async {
    await incomeBox.put(income.id, income);
  }
  
  static Future<void> deleteIncome(String id) async {
    await incomeBox.delete(id);
  }
  
  static List<IncomeModel> getIncomesByDate(DateTime date) {
    return incomeBox.values.where((income) {
      return income.date.year == date.year &&
             income.date.month == date.month &&
             income.date.day == date.day;
    }).toList();
  }
  
  // Category operations
  static Box<CategoryModel> get categoryBox => Hive.box<CategoryModel>(categoryBoxName);
  
  static Future<void> addCategory(CategoryModel category) async {
    await categoryBox.put(category.id, category);
  }
  
  static Future<void> updateCategory(CategoryModel category) async {
    await categoryBox.put(category.id, category);
  }
  
  static Future<void> deleteCategory(String id) async {
    final category = categoryBox.get(id);
    if (category != null && !category.isProtected) {
      await categoryBox.delete(id);
    }
  }
  
  static List<CategoryModel> getAllCategories() {
    return categoryBox.values.toList();
  }

  // Workout operations
  static Box<WorkoutModel> get workoutBox => Hive.box<WorkoutModel>(workoutBoxName);

  static Future<void> addWorkout(WorkoutModel workout) async {
    await workoutBox.put(workout.id, workout);
  }

  static Future<void> deleteWorkout(String id) async {
    await workoutBox.delete(id);
  }

  static List<WorkoutModel> getWorkoutsByDay(String day) {
    return workoutBox.values.where((w) => w.day == day).toList();
  }

  static List<WorkoutModel> getAllWorkouts() {
    return workoutBox.values.toList();
  }

  // Work task operations
  static Box<WorkTaskModel> get workTaskBox => Hive.box<WorkTaskModel>(workTaskBoxName);

  static Future<void> addWorkTask(WorkTaskModel task) async {
    await workTaskBox.put(task.id, task);
  }

  static Future<void> updateWorkTask(WorkTaskModel task) async {
    await workTaskBox.put(task.id, task);
  }

  static Future<void> deleteWorkTask(String id) async {
    await workTaskBox.delete(id);
  }

  static List<WorkTaskModel> getAllWorkTasks() {
    return workTaskBox.values.toList();
  }

  static List<WorkTaskModel> getWorkTasksByType(TaskType type) {
    return workTaskBox.values.where((t) => t.type == type).toList();
  }
}
